# Site settings
title: danthedev
email: dan@danthedev.com
description: > # this means to ignore newlines until "baseurl:"
  The personal website of Dan Prince
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://danthedev.com" # the base hostname & protocol for your site
twitter_username: workshydev
github_username: danprince
permalink: "/:year/:month/:day/:title"
image:
  src: "/img/banner.jpg"

# Build settings
markdown: kramdown
