# Site settings
title: danthedev
email: dan@danthedev.com
description: >
  Thoughts of another programmer.
baseurl: ""
url: "http://danthedev.com"
twitter_username: workshydev
github_username: danprince
permalink: "/:year/:month/:day/:title"
image:
  src: "/img/banner.jpg"

# Build settings
markdown: kramdown

# Sass settings
sass:
  style: :compressed
